#!/bin/sh
if [[ $EUID != 0 ]]; then
    echo "Root required"
    exit 1
fi

echo 5 > /proc/sys/vm/laptop_mode
echo 20 > /proc/sys/vm/dirty_ratio
echo 10 > /proc/sys/vm/dirty_background_ratio
echo 4500 > /proc/sys/vm/dirty_expire_centisecs
echo 1500 > /proc/sys/vm/dirty_writeback_centisecs
echo 0 > /proc/sys/kernel/nmi_watchdog
echo 1 > /sys/module/snd_hda_intel/parameters/power_save


modprobe msr
x86_energy_perf_policy powersave

for i in /sys/bus/pci/devices/*/power/control; do echo 'auto' > $i;done
echo powersave > /sys/module/pcie_aspm/parameters/policy
for i in /sys/class/scsi_host/*/link_power_management_policy;do echo 'min_power' > $i;done
for i in /sys/bus/usb/devices/*/power/autosuspend; do echo '1' > $i;done

WIFI=$(find /sys/class/net/*/ | grep wireless | head -n 1 | sed -s -e "s#^/sys.*net/##" -e "s#/wireless.*\$##")
iw dev $WIFI set power_save on
